### ISSUE TITLE
Support for (unsigned int) hex notation

### ISSUE THREAD

**Issue by philippotto** [ShaderFrog/glsl-parser#1]
glsl-parser does not support this (valid) GLSL 3000 code:

```js
    void main() {
      highp uint value = 0x1234u;
    }
```

The following error is thrown:

```
SyntaxError (peg$SyntaxError) {
    expected: [
      {
        description: 'asignment',
        type: 'other',
      },
      {
        ignoreCase: false,
        text: '^',
        type: 'literal',
      },
      {
        ignoreCase: false,
        text: '|',
        type: 'literal',
      },
      {
        ignoreCase: false,
        text: '&&',
        type: 'literal',
      },
      {
        ignoreCase: false,
        text: '^^',
        type: 'literal',
      },
      {
        ignoreCase: false,
        text: '||',
        type: 'literal',
      },
      {
        ignoreCase: false,
        text: '?',
        type: 'literal',
      },
      {
        ignoreCase: false,
        text: ',',
        type: 'literal',
      },
      {
        ignoreCase: false,
        text: ';',
        type: 'literal',
      },
    ],
    found: 'x',
    location: {
      end: {
        column: 28,
        line: 3,
        offset: 46,
      },
      source: undefined,
      start: {
        column: 27,
        line: 3,
        offset: 45,
      },
    },
    message: 'Expected "&&", ",", ";", "?", "^", "^^", "|", "||", or asignment but "x" found.',
  }
```

I had to rewrite my code to not use the hex notation, so that I could use your package in a test. Maybe it is easy to fix? Thanks for the package!

**Comment by AndrewRayCode** [comment]
Thanks for the report! My first bug ✋😊🤚

Fixed in https://github.com/ShaderFrog/glsl-parser/commit/f4f54a54e71c43454f397fa21cb2bd6e7eac13f6 and published new version `0.3.0`, `npm install --save @shaderfrog/glsl-parser@0.3.0`

The peggy grammar in this library supported hex integers, as I copied the grammar from the Khronos spec, but I didn't have a test for them. The Khronos spec doesn't use a Peg grammar so their order doesn't matter. In the Shaderfrog parser, I had "float" first before "integer", as that's the order in the Khronos spec. So "float" consumed "0" in "0x..." and then barfed once it hit "x" because it thought it successfully parsed a float.
