### ISSUE TITLE
parser.parse fails on struct with #ifdef

### ISSUE THREAD

**Issue by yorkie** [ShaderFrog/glsl-parser#36]
The parse() seems to fail a `struct` with preprocessor just like `#ifdef`:

```js
import { parser } from '@shaderfrog/glsl-parser';

let source = `
struct Foo {
  vec3 pos;
#ifdef USE_FOLLOW
  vec3 follow;
#endif
};
`;
try {
  parser.parse(source);
} catch (err) {
  console.warn(err.format([{ text: source }]));
}
```

The error:

```
Error: Expected function prototype, function prototype scope, precision statement, prepocessor, or whitespace but "s" found.
 --> undefined:2:1
  |
2 | struct Foo {
  | ^
```

**Comment by AndrewRayCode** [comment]
You need to preprocess the source string first! https://github.com/ShaderFrog/glsl-parser?tab=readme-ov-file#preprocessing

**Comment by yorkie** [comment]
@AndrewRayCode Thank you for this reply, unfortunately preprocess doesn't work for my usecase, I wanna modify the glsl AST and generate the source that should include the preprocessors.

**Comment by yorkie** [comment]
And at https://github.com/ShaderFrog/glsl-parser/blob/main/src/parser/glsl-grammar.pegjs#L1175:

```js
statement_list = (statement / preprocessor)+
```

The glsl parser supports the preprocessors in statement list and others, but not getting considered at some like `struct_declaration_list`.

**Comment by AndrewRayCode** [comment]
@yorkie That use case unfortunately is not supported by the parser.

Technically no preprocessor statements are valid GLSL. A program source code string should be fully preprocessed before being handed off to the parser. [The official grammar](https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.pdf) does not support preprocessor lines:

> statement_list :
>   statement
>  statement_list statement

I think my intention of including a preprocessor line in this GLSL Grammar was so that you can avoid preprocessing _some_ programs, if you want, if they only contain top level preprocessor lines. I think it would be too complicated in the peg grammar to try to support arbitrary preprocessor lines in arbitrary places. If I were to make any feature change I think it makes more sense to remove the preprocessor line from the parser peg grammar.

**Comment by yorkie** [comment]
@AndrewRayCode I see! Thank you for this explanation, in short, thanks a lot!
